<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-users';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

?>

<div class="zui-toolbar">
    <div class="zui-toolbar-primary">
        <h2>Groups</h2>
    </div>
    <div class="zui-toolbar-secondary">
        <a href="<?php echo $this->url('admin/usermanagement/groups/create'); ?>" class="zui-button">Create</a>
    </div>
</div>

<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_DEFAULT); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_WARNING); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_INFO); ?>

<?php if (count($this->groups) === 0) { ?>
    <div class="zui-alert">
        <p>
            No groups found.
        </p>
    </div>
<?php } else { ?>
    <table class="zui-table zui-table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th class="zui-text-right" style="width: 200px;">Operations</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->groups as $group) { ?>
                <tr>
                    <td style="width: 250px;"><?php echo $this->escapeHtml($group->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($group->getDescription()); ?></td>
                    <td class="zui-text-right">
                        <a href="<?php echo $this->url('admin/usermanagement/groups/update', [
                            'id' => $group->getId(),
                        ]); ?>">Update</a>
                        -
                        <a href="<?php echo $this->url('admin/usermanagement/groups/delete', [
                            'id' => $group->getId(),
                        ]); ?>">Delete</a>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } ?>
