<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-users';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

$this->groupForm->setAttribute('action', $this->url('admin/usermanagement/groups/update', [
    'id' => $this->group->getId(),
]));
$this->groupForm->setAttribute('method', 'post');
$this->groupForm->get('accounts')->setAttribute('data-zui-select2-url', $this->url('lookup/account'));
$this->groupForm->prepare();

?>

<h2>Update Group</h2>

<?php echo $this->form()->openTag($this->groupForm); ?>
<?php echo $this->formHidden($this->groupForm->get('token')); ?>

<div class="zui-field-group">
    <?php echo $this->formLabel($this->groupForm->get('name')); ?>
    <?php echo $this->formText($this->groupForm->get('name')); ?>
    <?php echo $this->zourceFormDescription($this->groupForm->get('name')); ?>
    <?php echo $this->formElementErrors($this->groupForm->get('name')); ?>
</div>

<div class="zui-field-group">
    <?php echo $this->formLabel($this->groupForm->get('description')); ?>
    <?php echo $this->formTextarea($this->groupForm->get('description')); ?>
    <?php echo $this->zourceFormDescription($this->groupForm->get('description')); ?>
    <?php echo $this->formElementErrors($this->groupForm->get('description')); ?>
</div>

<div class="zui-field-group">
    <?php echo $this->formLabel($this->groupForm->get('accounts')); ?>
    <?php echo $this->zourceFormSelect2($this->groupForm->get('accounts')); ?>
    <?php echo $this->zourceFormDescription($this->groupForm->get('accounts')); ?>
    <?php echo $this->formElementErrors($this->groupForm->get('accounts')); ?>
</div>

<div class="zui-field-group">
    <span class="zui-form-label"><?php echo $this->groupForm->get('description')->getLabel(); ?></span>

    <div class="zui-field-group-inner">
        <div>
            <?php echo $this->formMultiCheckbox($this->groupForm->get('permissions')); ?>
        </div>
    </div>

    <?php echo $this->zourceFormDescription($this->groupForm->get('description')); ?>
    <?php echo $this->formElementErrors($this->groupForm->get('description')); ?>
</div>

<div class="zui-buttons-container">
    <div class="zui-buttons">
        <input type="submit" value="Save">
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>
