<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('layoutUserProfileTitle');
$this->placeholder('layout')->pageMenu = 'user-settings';

?>

<h2><?php echo $this->translate('pageUserSecurityTitle'); ?></h2>

<h3>Two-factor authentication</h3>

<?php if ($this->account->hasTwoFactorAuthentication()) { ?>
    <p>
        <span class="zui-status zui-status-green">Enabled</span>
        Two-factor authentication is currently enabled
    </p>

    <ul>
        <li>
            <a href="<?php echo $this->url('settings/security/recovery-codes'); ?>">
                Save your recovery codes</a> in a safe place. They will allow you to access your account if you ever lose your phone.
            </a>
        </li>
        <li>
            We do not recommend that you do, but you can <a href="<?php echo $this->url('settings/security/tfa-disable'); ?>">disable two-factor authentication</a>.
        </li>
    </ul>
<?php } else { ?>
    <p>
        <span class="zui-status zui-status-red">Disabled</span>
        Two-factor authentication is currently disabled
    </p>

    <p>
        <a href="<?php echo $this->url('settings/security/tfa-enable'); ?>">Would you like to enable Two-factor authentication?</a>
    </p>
<?php } ?>

<h3>Sessions</h3>

<p>
    This is a list of devices that have logged into your account. Revoke any sessions that you do not recognize.
</p>

<table class="zui-table zui-table-bordered">
    <thead>
        <tr>
            <th>IP Address</th>
            <th>User agent</th>
            <th>Location</th>
            <th>Signed in</th>
            <th>Last active</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->sessions as $session) { ?>
        <tr>
            <td><?php echo $this->escapeHtml($session['remoteAddress']); ?></td>
            <td title="<?php echo $this->escapeHtmlAttr($session['userAgent']); ?>">
                <?php echo (string)$this->userAgentParser->parse($session['userAgent']); ?><br>
                <span style="font-size: 80%;"><?php echo $session['userAgent']; ?></span>
            </td>
            <td><?php

                $lookupEntry = $this->remoteAddressLookup->lookup($session['remoteAddress']);
                $location = $lookupEntry ? $lookupEntry->getLocation() : null;

                echo $location ?: '<em>Unknown</em>';

                ?></td>
            <td><?php echo $session['creationDate']->format('r'); ?></td>
            <td><?php echo $session['lastModified']->format('r'); ?></td>
            <td class="text-right">
                <?php if (session_id() !== $session['id']) { ?>
                    <a href="<?php echo $this->url('settings/security/revoke-session', [
                        'id' => $session['id'],
                    ]); ?>" class="zui-button">
                <?php } else { ?>
                    <a href="<?php echo $this->url('settings/security/revoke-session', [
                        'id' => $session['id'],
                    ]); ?>" class="zui-button" disabled="disabled" aria-disabled="true">
                <?php } ?>
                        Revoke
                    </a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
