<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageContactsTitle');
$this->placeholder('layout')->pageMenu = 'contacts-directory';

$this->contactForm->setAttribute('action', $this->url('contacts/person/create'));
$this->contactForm->setAttribute('method', 'post');
$this->contactForm->prepare();

?>

<h2>Create Person</h2>

<?php echo $this->form()->openTag($this->contactForm); ?>
<?php echo $this->formHidden($this->contactForm->get('token')); ?>
<?php echo $this->zourceContactForm()->render($this->contactForm, 'person'); ?>

<div class="zui-buttons-container">
    <div class="zui-buttons">
        <?php echo $this->formSubmit($this->contactForm->get('submit')); ?>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>
<?php echo $this->zourceContactForm()->renderAdditional($this->contactForm, 'person'); ?>
