<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('layoutUserProfileTitle');
$this->placeholder('layout')->pageMenu = 'user-settings';

?>

<h2><?php echo $this->translate('pageUserApplicationTitle'); ?></h2>

<div class="zui-tabs zui-horizontal-tabs">
    <ul class="zui-tabs-menu" role="tablist">
        <li role="presentation" class="zui-menu-item zui-active-tab">
            <a href="#authorized-applications" role="tab" aria-selected="true"><strong>Developer
                    applications</strong></a>
        </li>
        <li role="presentation" class="zui-menu-item">
            <a href="#tab2" role="tab" aria-selected="false"><strong>Authorized applications</strong></a>
        </li>
    </ul>

    <div class="zui-tabs-content">
        <div role="tabpanel" aria-hidden="true" id="authorized-applications" class="zui-tabs-pane zui-active-pane">
            <?php if (count($this->applications) === 0) { ?>
                <p>
                    No applications created yet, <a href="<?php echo $this->url('settings/applications/create'); ?>">would
                        you like to create one</a>?
                </p>
            <?php } else { ?>
                <table class="zui-table-striped">
                    <thead>
                        <tr>
                            <th>Appplication</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->applications as $application) { ?>
                            <tr>
                                <td>
                                    <a href="<?php echo $this->url('settings/applications/update', [
                                        'id' => $application->getClientId()->toString(),
                                    ]); ?>">
                                        <?php echo $this->escapeHtml($application->getName()); ?>
                                    </a><br/>
                                    <small>Client
                                        ID: <?php echo $this->escapeHtml($application->getClientId()); ?></small>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>

                <p>
                    <a href="<?php echo $this->url('settings/applications/create'); ?>" class="zui-button">Create</a>
                </p>
            <?php } ?>
        </div>

        <div role="tabpanel" aria-hidden="false" id="tab2" class="zui-tabs-pane">
            <p>
                No applications are authorized to access your account.
            </p>
        </div>
    </div>
</div>
