<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('layoutUserProfileTitle');
$this->placeholder('layout')->pageMenu = 'user-settings';

?>

<h2><?php echo $this->translate('pageUserApplicationTitle'); ?></h2>

<div class="zui-tabs zui-horizontal-tabs">
    <ul class="zui-tabs-menu" role="tablist">
        <li role="presentation" class="zui-menu-item zui-active-tab">
            <a href="#authorized-applications" role="tab" aria-selected="true"><strong>Authorized Applications</strong></a>
        </li>
        <li role="presentation" class="zui-menu-item">
            <a href="#tab2" role="tab" aria-selected="false"><strong>Incoming</strong></a>
        </li>
    </ul>

    <div class="zui-tabs-content">
        <div role="tabpanel" aria-hidden="true" id="authorized-applications" class="zui-tabs-pane zui-active-pane">
            <table class="zui-table-striped">
                <thead>
                    <tr>
                        <th>Appplication</th>
                        <th class="text-right">Options</th>
                    </tr>
                </thead>
                <tbody>
                    <?php for ($i = 0; $i < 5; ++$i) { ?>
                        <tr>
                            <td width="70%">Demo Application <?php echo $i; ?></td>
                            <td width="30%" class="text-right">
                                <a href="" class="zui-button">
                                    <i class="zui-icon zui-icon-trash"></i>
                                    Revoke
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>

        <div role="tabpanel" aria-hidden="false" id="tab2" class="zui-tabs-pane">
            Hello Item 2
        </div>
    </div>
</div>
