<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->dashboard->getName();

$gadgetContainer = $this->dashboard->getGadgetContainer();

?>

<div class="zui-toolbar" style="margin-bottom: 20px;">
    <div class="zui-toolbar-primary">
    </div>

    <div class="zui-toolbar-secondary">
        <a href="" class="zui-button zui-button-subtle" data-zui-dialog-trigger="#zource-dialog-add-gadget">
            Add gadget
        </a>
        <a href="" class="zui-button zui-button-subtle" data-zui-dialog-trigger="#zource-dialog-set-layout">
            Set layout
        </a>
    </div>
</div>

<?php echo $this->zourceGadgetContainer($gadgetContainer, [
    'load_url' => 'gadget/load',
    'update_url' => 'gadget/update',
    'update_container_url' => $this->url('gadget/update-container', [
        'id' => $this->dashboard->getGadgetContainer()->getId(),
    ]),
]); ?>

<div class="zui-dialog zui-dialog-large" id="zource-dialog-add-gadget">
    <div class="zui-dialog-header">
        <h2>Add Gadget</h2>
        <i class="zui-icon zui-icon-x"></i>
    </div>

    <div class="zui-dialog-page">
        <div class="zui-dialog-menu">
            <form class="zource-dialog-gadgets-search">
                <input type="" name="" value="">
            </form>

            <nav class="zui-navgroup zui-navgroup-vertical">
                <div class="zui-navgroup-inner">
                    <div class="zui-nav-heading">
                        <strong>Categories</strong>
                    </div>

                    <ul class="zui-nav">
                        <?php foreach ($this->gadgetCategories as $category) { ?>
                        <li data-zui-gadget-category="<?php echo $this->escapeHtmlAttr($category['key']); ?>">
                            <a href="">
                                <?php echo $this->escapeHtml($category['label']); ?>
                                <span class="zui-badge" style="float: right;">
                                    <?php echo $this->escapeHtml($category['gadgetCount']); ?>
                                </span>
                            </a>
                        </li>
                        <?php } ?>
                    </ul>
                </div>
            </nav>
        </div>

        <div class="zui-dialog-page-body">
            <div class="zui-dialog-panel">
                <ul>
                    <?php foreach ($this->gadgets as $gadgetId => $gadget) { ?>
                    <li>
                        <img src="<?php echo $this->escapeHtml($gadget['thumbnail']); ?>" alt="<?php echo $this->escapeHtmlAttr($gadget['title']); ?>">

                        <h3><?php echo $this->escapeHtml($gadget['title']); ?></h3>

                        <p><?php echo $this->escapeHtml($gadget['description']); ?></p>

                        <button data-zui-gadget="<?php echo $this->escapeHtmlAttr($gadgetId); ?>">Add</button>
                    </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>

    <div class="zui-dialog-footer">
        <div class="zui-dialog-footer-left">
            <div class="zui-dialog-hint">
                Choose a gadget you would like to add.
            </div>
        </div>

        <div class="zui-dialog-footer-right">
            <a href="#" data-zui-dialog-button="cancel">Cancel</a>
        </div>
    </div>
</div>

<div class="zui-dialog zui-dialog-medium" id="zource-dialog-set-layout">
    <div class="zui-dialog-header">
        <h2>Set Layout</h2>
        <i class="zui-icon zui-icon-x"></i>
    </div>

    <div class="zui-dialog-page">
        <div class="zui-dialog-page-body">
            <div class="zui-dialog-panel">
                <ul>
                    <li><img src="" alt="100" data-zource-container-layout="100" class="zource-dialog-set-layout-item"></li>
                    <li><img src="" alt="50-50" data-zource-container-layout="50-50" class="zource-dialog-set-layout-item"></li>
                    <li><img src="" alt="33-67" data-zource-container-layout="33-67" class="zource-dialog-set-layout-item"></li>
                    <li><img src="" alt="67-33" data-zource-container-layout="67-33" class="zource-dialog-set-layout-item"></li>
                    <li><img src="" alt="33-33-34" data-zource-container-layout="33-33-34" class="zource-dialog-set-layout-item"></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="zui-dialog-footer">
        <div class="zui-dialog-footer-left">
            <div class="zui-dialog-hint">
                Choose your preferred gadget container layout.
            </div>
        </div>

        <div class="zui-dialog-footer-right">
            <a href="#" data-zui-dialog-button="cancel">Cancel</a>
        </div>
    </div>
</div>
