<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->dashboard->getName();

$widgetContainer = $this->dashboard->getWidgetContainer();

?>

<div class="zui-toolbar" style="margin-bottom: 20px;">
    <div class="zui-toolbar-primary">
    </div>

    <div class="zui-toolbar-secondary">
            <a href="" class="zui-button zui-button-subtle" data-zui-dialog-trigger="#zource-dialog-add-widget">
                Add widget
            </a>
            <a href="" class="zui-button zui-button-subtle" data-zui-dialog-trigger="#zource-dialog-set-layout">
                Set layout
            </a>
    </div>
</div>

<?php echo $this->zourceWidgetContainer($widgetContainer); ?>

<div class="zui-dialog zui-dialog-large" id="zource-dialog-add-widget" data-zource-widgets-url="<?php echo $this->url('dashboard/widget-dialog'); ?>">
    <div class="zui-dialog-header">
        <h2>Add Widget</h2>
        <i class="zui-icon zui-icon-x"></i>
    </div>

    <div class="zui-dialog-page">
        <div class="zui-dialog-menu">
            <form class="zource-widgete-dialog-search">
                <input type="" name="" value="">
            </form>

            <nav class="zui-navgroup zui-navgroup-vertical">
                <div class="zui-navgroup-inner">
                    <div class="zui-nav-heading">
                        <strong>Categories</strong>
                    </div>

                    <ul class="zui-nav">
                        <li><a href="http://example.com">Item <span class="zui-badge" style="float: right;">123</span></a></li>
                    </ul>
                </div>
            </nav>
        </div>

        <div class="zui-dialog-page-body">
            <div class="zui-dialog-panel">
                <p>This is the content of the dialog panel.</p>
            </div>

            <div class="zui-dialog-panel" aria-hidden="true">
                <p>This is the content of another dialog panel.</p>

                <div style="height: 2000px;"></div>

                <p>Cool eh?</p>
            </div>

            <div class="zui-dialog-panel" aria-hidden="true">
                <p>This is another awesome panel.</p>

                <div style="height: 2000px;"></div>

                <p>Cool eh?</p>
            </div>
        </div>
    </div>

    <div class="zui-dialog-footer">
        <div class="zui-dialog-footer-left">
            <div class="zui-dialog-hint">
                Choose a widget you would like to add.
            </div>
        </div>

        <div class="zui-dialog-footer-right">
            <a href="#" data-zui-dialog-button="cancel">Cancel</a>
        </div>
    </div>
</div>

<div class="zui-dialog zui-dialog-medium" id="zource-dialog-set-layout">
    <div class="zui-dialog-header">
        <h2>Set Layout</h2>
        <i class="zui-icon zui-icon-x"></i>
    </div>

    <div class="zui-dialog-page">
        <div class="zui-dialog-page-body">
            <div class="zui-dialog-panel">
                <ul>
                    <li><img src="" alt="100" data-zource-container-layout="100" class="zource-dialog-set-layout-item"></li>
                    <li><img src="" alt="50-50" data-zource-container-layout="50-50" class="zource-dialog-set-layout-item"></li>
                    <li><img src="" alt="33-67" data-zource-container-layout="33-67" class="zource-dialog-set-layout-item"></li>
                    <li><img src="" alt="67-33" data-zource-container-layout="67-33" class="zource-dialog-set-layout-item"></li>
                    <li><img src="" alt="33-33-34" data-zource-container-layout="33-33-34" class="zource-dialog-set-layout-item"></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="zui-dialog-footer">
        <div class="zui-dialog-footer-left">
            <div class="zui-dialog-hint">
                Choose your preferred widget container layout.
            </div>
        </div>

        <div class="zui-dialog-footer-right">
            <a href="#" data-zui-dialog-button="cancel">Cancel</a>
        </div>
    </div>
</div>
