<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageDashboardTitle');

?>

<div class="zui-gadgets zui-gadget-2col">
    <div class="zui-gadget-column">
        <div class="zui-gadget">
            <div class="zui-gadget-header">
                <h3>Welcome to Zource</h3>
            </div>
            <div class="zui-gadget-body">
                <p>
                    Maecenas cursus luctus metus, et suscipit urna. Sed lacinia nec turpis in aliquet. Curabitur porttitor
                    tortor in ornare aliquam. Phasellus eu tortor scelerisque velit faucibus tristique a nec eros. Nullam
                    aliquam felis tortor, vel ultricies dolor tristique et. Etiam semper, tortor at iaculis commodo, dolor
                    quam lobortis risus, in facilisis massa elit non odio. Donec lacinia augue quis massa molestie, blandit
                    egestas eros vehicula. Praesent risus nibh, placerat quis felis id, commodo lacinia felis. Morbi non enim
                    non felis convallis tempus sed et justo. Cras odio odio, blandit eu massa vitae, sagittis maximus diam.
                    Mauris ac vehicula tellus. Praesent mauris ipsum, rhoncus non hendrerit non, aliquam non est. Donec tempor
                    convallis elit, ut maximus justo auctor eu. Suspendisse a sapien egestas, blandit odio a, consequat justo.
                </p>

                <p>
                    Nulla fringilla orci sit amet nunc elementum, eu faucibus massa fringilla. Fusce at auctor risus. Proin
                    condimentum, libero non tincidunt placerat, tortor dui molestie elit, et sodales elit elit id libero.
                    Fusce in massa urna. Phasellus pharetra sem non hendrerit placerat. Aenean vel euismod lectus. Aliquam
                    dignissim nec diam at hendrerit. Ut et ipsum in enim posuere accumsan. Nullam dignissim congue quam eget
                    interdum. Nulla auctor semper euismod. Ut imperdiet ligula cursus, pulvinar sem eu, sagittis dolor.
                </p>

                <p>
                    Nunc a felis velit. Nam nec ipsum ultricies, luctus enim id, egestas nulla. Praesent eros neque, suscipit
                    in ante eu, varius consequat eros. Suspendisse potenti. Proin iaculis, arcu nec venenatis volutpat, quam
                    est euismod nibh, ut dictum nulla mauris eget enim. Duis fringilla quam non dignissim lacinia. Aenean
                    sollicitudin, arcu in ultricies vulputate, libero sem mollis augue, ac aliquet lectus erat sodales ipsum.
                    Nunc ultricies tincidunt varius. Vivamus et mauris non risus vulputate varius. Suspendisse sed quam arcu.
                    Donec et magna velit. Mauris tincidunt nisl neque. Integer ultricies sed arcu et porttitor. Maecenas
                    pharetra, neque placerat volutpat lacinia, est lectus gravida tellus, et vestibulum augue odio ut lectus.
                    In sit amet ultricies urna. Quisque aliquam nisi ligula.
                </p>
            </div>
        </div>

        <div class="zui-gadget">
            <div class="zui-gadget-header">
                <h3>Welcome to Zource</h3>
            </div>
            <div class="zui-gadget-body">
                <p>
                    Maecenas cursus luctus metus, et suscipit urna. Sed lacinia nec turpis in aliquet. Curabitur porttitor
                    tortor in ornare aliquam. Phasellus eu tortor scelerisque velit faucibus tristique a nec eros. Nullam
                    aliquam felis tortor, vel ultricies dolor tristique et. Etiam semper, tortor at iaculis commodo, dolor
                    quam lobortis risus, in facilisis massa elit non odio. Donec lacinia augue quis massa molestie, blandit
                    egestas eros vehicula. Praesent risus nibh, placerat quis felis id, commodo lacinia felis. Morbi non enim
                    non felis convallis tempus sed et justo. Cras odio odio, blandit eu massa vitae, sagittis maximus diam.
                    Mauris ac vehicula tellus. Praesent mauris ipsum, rhoncus non hendrerit non, aliquam non est. Donec tempor
                    convallis elit, ut maximus justo auctor eu. Suspendisse a sapien egestas, blandit odio a, consequat justo.
                </p>

                <p>
                    Nulla fringilla orci sit amet nunc elementum, eu faucibus massa fringilla. Fusce at auctor risus. Proin
                    condimentum, libero non tincidunt placerat, tortor dui molestie elit, et sodales elit elit id libero.
                    Fusce in massa urna. Phasellus pharetra sem non hendrerit placerat. Aenean vel euismod lectus. Aliquam
                    dignissim nec diam at hendrerit. Ut et ipsum in enim posuere accumsan. Nullam dignissim congue quam eget
                    interdum. Nulla auctor semper euismod. Ut imperdiet ligula cursus, pulvinar sem eu, sagittis dolor.
                </p>

                <p>
                    Nunc a felis velit. Nam nec ipsum ultricies, luctus enim id, egestas nulla. Praesent eros neque, suscipit
                    in ante eu, varius consequat eros. Suspendisse potenti. Proin iaculis, arcu nec venenatis volutpat, quam
                    est euismod nibh, ut dictum nulla mauris eget enim. Duis fringilla quam non dignissim lacinia. Aenean
                    sollicitudin, arcu in ultricies vulputate, libero sem mollis augue, ac aliquet lectus erat sodales ipsum.
                    Nunc ultricies tincidunt varius. Vivamus et mauris non risus vulputate varius. Suspendisse sed quam arcu.
                    Donec et magna velit. Mauris tincidunt nisl neque. Integer ultricies sed arcu et porttitor. Maecenas
                    pharetra, neque placerat volutpat lacinia, est lectus gravida tellus, et vestibulum augue odio ut lectus.
                    In sit amet ultricies urna. Quisque aliquam nisi ligula.
                </p>
            </div>
        </div>

        <div class="zui-gadget">
            <div class="zui-gadget-header">
                <h3>Welcome to Zource</h3>
            </div>
            <div class="zui-gadget-body">
                <p>
                    Maecenas cursus luctus metus, et suscipit urna. Sed lacinia nec turpis in aliquet. Curabitur porttitor
                    tortor in ornare aliquam. Phasellus eu tortor scelerisque velit faucibus tristique a nec eros. Nullam
                    aliquam felis tortor, vel ultricies dolor tristique et. Etiam semper, tortor at iaculis commodo, dolor
                    quam lobortis risus, in facilisis massa elit non odio. Donec lacinia augue quis massa molestie, blandit
                    egestas eros vehicula. Praesent risus nibh, placerat quis felis id, commodo lacinia felis. Morbi non enim
                    non felis convallis tempus sed et justo. Cras odio odio, blandit eu massa vitae, sagittis maximus diam.
                    Mauris ac vehicula tellus. Praesent mauris ipsum, rhoncus non hendrerit non, aliquam non est. Donec tempor
                    convallis elit, ut maximus justo auctor eu. Suspendisse a sapien egestas, blandit odio a, consequat justo.
                </p>

                <p>
                    Nulla fringilla orci sit amet nunc elementum, eu faucibus massa fringilla. Fusce at auctor risus. Proin
                    condimentum, libero non tincidunt placerat, tortor dui molestie elit, et sodales elit elit id libero.
                    Fusce in massa urna. Phasellus pharetra sem non hendrerit placerat. Aenean vel euismod lectus. Aliquam
                    dignissim nec diam at hendrerit. Ut et ipsum in enim posuere accumsan. Nullam dignissim congue quam eget
                    interdum. Nulla auctor semper euismod. Ut imperdiet ligula cursus, pulvinar sem eu, sagittis dolor.
                </p>

                <p>
                    Nunc a felis velit. Nam nec ipsum ultricies, luctus enim id, egestas nulla. Praesent eros neque, suscipit
                    in ante eu, varius consequat eros. Suspendisse potenti. Proin iaculis, arcu nec venenatis volutpat, quam
                    est euismod nibh, ut dictum nulla mauris eget enim. Duis fringilla quam non dignissim lacinia. Aenean
                    sollicitudin, arcu in ultricies vulputate, libero sem mollis augue, ac aliquet lectus erat sodales ipsum.
                    Nunc ultricies tincidunt varius. Vivamus et mauris non risus vulputate varius. Suspendisse sed quam arcu.
                    Donec et magna velit. Mauris tincidunt nisl neque. Integer ultricies sed arcu et porttitor. Maecenas
                    pharetra, neque placerat volutpat lacinia, est lectus gravida tellus, et vestibulum augue odio ut lectus.
                    In sit amet ultricies urna. Quisque aliquam nisi ligula.
                </p>
            </div>
        </div>
    </div>
    <div class="zui-gadget-column">

        <div class="zui-gadget">
            <div class="zui-gadget-header">
                <h3>Welcome to Zource</h3>
            </div>
            <div class="zui-gadget-body">
                <p>
                    Maecenas cursus luctus metus, et suscipit urna. Sed lacinia nec turpis in aliquet. Curabitur porttitor
                    tortor in ornare aliquam. Phasellus eu tortor scelerisque velit faucibus tristique a nec eros. Nullam
                    aliquam felis tortor, vel ultricies dolor tristique et. Etiam semper, tortor at iaculis commodo, dolor
                    quam lobortis risus, in facilisis massa elit non odio. Donec lacinia augue quis massa molestie, blandit
                    egestas eros vehicula. Praesent risus nibh, placerat quis felis id, commodo lacinia felis. Morbi non enim
                    non felis convallis tempus sed et justo. Cras odio odio, blandit eu massa vitae, sagittis maximus diam.
                    Mauris ac vehicula tellus. Praesent mauris ipsum, rhoncus non hendrerit non, aliquam non est. Donec tempor
                    convallis elit, ut maximus justo auctor eu. Suspendisse a sapien egestas, blandit odio a, consequat justo.
                </p>

                <p>
                    Nulla fringilla orci sit amet nunc elementum, eu faucibus massa fringilla. Fusce at auctor risus. Proin
                    condimentum, libero non tincidunt placerat, tortor dui molestie elit, et sodales elit elit id libero.
                    Fusce in massa urna. Phasellus pharetra sem non hendrerit placerat. Aenean vel euismod lectus. Aliquam
                    dignissim nec diam at hendrerit. Ut et ipsum in enim posuere accumsan. Nullam dignissim congue quam eget
                    interdum. Nulla auctor semper euismod. Ut imperdiet ligula cursus, pulvinar sem eu, sagittis dolor.
                </p>

                <p>
                    Nunc a felis velit. Nam nec ipsum ultricies, luctus enim id, egestas nulla. Praesent eros neque, suscipit
                    in ante eu, varius consequat eros. Suspendisse potenti. Proin iaculis, arcu nec venenatis volutpat, quam
                    est euismod nibh, ut dictum nulla mauris eget enim. Duis fringilla quam non dignissim lacinia. Aenean
                    sollicitudin, arcu in ultricies vulputate, libero sem mollis augue, ac aliquet lectus erat sodales ipsum.
                    Nunc ultricies tincidunt varius. Vivamus et mauris non risus vulputate varius. Suspendisse sed quam arcu.
                    Donec et magna velit. Mauris tincidunt nisl neque. Integer ultricies sed arcu et porttitor. Maecenas
                    pharetra, neque placerat volutpat lacinia, est lectus gravida tellus, et vestibulum augue odio ut lectus.
                    In sit amet ultricies urna. Quisque aliquam nisi ligula.
                </p>
            </div>
        </div>

        <div class="zui-gadget">
            <div class="zui-gadget-header">
                <h3>Welcome to Zource</h3>
            </div>
            <div class="zui-gadget-body">
                <p>
                    Maecenas cursus luctus metus, et suscipit urna. Sed lacinia nec turpis in aliquet. Curabitur porttitor
                    tortor in ornare aliquam. Phasellus eu tortor scelerisque velit faucibus tristique a nec eros. Nullam
                    aliquam felis tortor, vel ultricies dolor tristique et. Etiam semper, tortor at iaculis commodo, dolor
                    quam lobortis risus, in facilisis massa elit non odio. Donec lacinia augue quis massa molestie, blandit
                    egestas eros vehicula. Praesent risus nibh, placerat quis felis id, commodo lacinia felis. Morbi non enim
                    non felis convallis tempus sed et justo. Cras odio odio, blandit eu massa vitae, sagittis maximus diam.
                    Mauris ac vehicula tellus. Praesent mauris ipsum, rhoncus non hendrerit non, aliquam non est. Donec tempor
                    convallis elit, ut maximus justo auctor eu. Suspendisse a sapien egestas, blandit odio a, consequat justo.
                </p>

                <p>
                    Nulla fringilla orci sit amet nunc elementum, eu faucibus massa fringilla. Fusce at auctor risus. Proin
                    condimentum, libero non tincidunt placerat, tortor dui molestie elit, et sodales elit elit id libero.
                    Fusce in massa urna. Phasellus pharetra sem non hendrerit placerat. Aenean vel euismod lectus. Aliquam
                    dignissim nec diam at hendrerit. Ut et ipsum in enim posuere accumsan. Nullam dignissim congue quam eget
                    interdum. Nulla auctor semper euismod. Ut imperdiet ligula cursus, pulvinar sem eu, sagittis dolor.
                </p>

                <p>
                    Nunc a felis velit. Nam nec ipsum ultricies, luctus enim id, egestas nulla. Praesent eros neque, suscipit
                    in ante eu, varius consequat eros. Suspendisse potenti. Proin iaculis, arcu nec venenatis volutpat, quam
                    est euismod nibh, ut dictum nulla mauris eget enim. Duis fringilla quam non dignissim lacinia. Aenean
                    sollicitudin, arcu in ultricies vulputate, libero sem mollis augue, ac aliquet lectus erat sodales ipsum.
                    Nunc ultricies tincidunt varius. Vivamus et mauris non risus vulputate varius. Suspendisse sed quam arcu.
                    Donec et magna velit. Mauris tincidunt nisl neque. Integer ultricies sed arcu et porttitor. Maecenas
                    pharetra, neque placerat volutpat lacinia, est lectus gravida tellus, et vestibulum augue odio ut lectus.
                    In sit amet ultricies urna. Quisque aliquam nisi ligula.
                </p>
            </div>
        </div>

        <div class="zui-gadget">
            <div class="zui-gadget-header">
                <h3>Welcome to Zource</h3>
            </div>
            <div class="zui-gadget-body">
                <p>
                    Maecenas cursus luctus metus, et suscipit urna. Sed lacinia nec turpis in aliquet. Curabitur porttitor
                    tortor in ornare aliquam. Phasellus eu tortor scelerisque velit faucibus tristique a nec eros. Nullam
                    aliquam felis tortor, vel ultricies dolor tristique et. Etiam semper, tortor at iaculis commodo, dolor
                    quam lobortis risus, in facilisis massa elit non odio. Donec lacinia augue quis massa molestie, blandit
                    egestas eros vehicula. Praesent risus nibh, placerat quis felis id, commodo lacinia felis. Morbi non enim
                    non felis convallis tempus sed et justo. Cras odio odio, blandit eu massa vitae, sagittis maximus diam.
                    Mauris ac vehicula tellus. Praesent mauris ipsum, rhoncus non hendrerit non, aliquam non est. Donec tempor
                    convallis elit, ut maximus justo auctor eu. Suspendisse a sapien egestas, blandit odio a, consequat justo.
                </p>

                <p>
                    Nulla fringilla orci sit amet nunc elementum, eu faucibus massa fringilla. Fusce at auctor risus. Proin
                    condimentum, libero non tincidunt placerat, tortor dui molestie elit, et sodales elit elit id libero.
                    Fusce in massa urna. Phasellus pharetra sem non hendrerit placerat. Aenean vel euismod lectus. Aliquam
                    dignissim nec diam at hendrerit. Ut et ipsum in enim posuere accumsan. Nullam dignissim congue quam eget
                    interdum. Nulla auctor semper euismod. Ut imperdiet ligula cursus, pulvinar sem eu, sagittis dolor.
                </p>

                <p>
                    Nunc a felis velit. Nam nec ipsum ultricies, luctus enim id, egestas nulla. Praesent eros neque, suscipit
                    in ante eu, varius consequat eros. Suspendisse potenti. Proin iaculis, arcu nec venenatis volutpat, quam
                    est euismod nibh, ut dictum nulla mauris eget enim. Duis fringilla quam non dignissim lacinia. Aenean
                    sollicitudin, arcu in ultricies vulputate, libero sem mollis augue, ac aliquet lectus erat sodales ipsum.
                    Nunc ultricies tincidunt varius. Vivamus et mauris non risus vulputate varius. Suspendisse sed quam arcu.
                    Donec et magna velit. Mauris tincidunt nisl neque. Integer ultricies sed arcu et porttitor. Maecenas
                    pharetra, neque placerat volutpat lacinia, est lectus gravida tellus, et vestibulum augue odio ut lectus.
                    In sit amet ultricies urna. Quisque aliquam nisi ligula.
                </p>
            </div>
        </div>

    </div>
</div>
