<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageDashboardManageTitle');
$this->placeholder('layout')->pageHeaderMenu = [
    $this->url('dashboard/create') => 'Create'
];

?>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th class="zui-text-right">Operations</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->dashboards as $dashboard) { ?>
        <tr>
            <td><?php echo $this->escapeHtml($dashboard->getName()); ?></td>
            <td class="zui-text-right">
                <a href="<?php echo $this->url('dashboard/select', [
                    'id' => $dashboard->getId(),
                ]); ?>">Select</a>
                -
                <a href="<?php echo $this->url('dashboard/delete', [
                    'id' => $dashboard->getId(),
                ]); ?>">Delete</a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->dashboards, 'sliding', 'partial/paginator', [
    'route' => 'dashboard/manage'
]); ?>
