<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('layoutUserProfileTitle');
$this->placeholder('layout')->pageMenu = 'user-settings';

?>

<h2><?php echo $this->translate('pageUserEmailTitle'); ?></h2>

<?php if (count($this->emailAddresses) === 0) { ?>
    <p>
        No e-mail addresses added yet.
    </p>
<?php } else { ?>
    <table class="zui-table-striped">
        <thead>
            <tr>
                <th>E-mail address</th>
                <th class="text-right">Verified</th>
                <th class="text-right">Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->emailAddresses as $emailAddress) { ?>
                <tr>
                    <td width="70%"><?php echo $this->escapeHtml($emailAddress->getAddress()); ?></td>
                    <td width="10%" class="text-right">
                        <?php if ($emailAddress->isVerified()) { ?>
                            <span class="zui-status zui-status-green zui-status-subtle">Verified</span>
                        <?php } else { ?>
                            <span class="zui-status zui-status-red zui-status-subtle">Not verified</span>
                        <?php } ?>
                    </td>
                    <td width="15%" class="text-right">
                        <?php if ($emailAddress->isVerified()) { ?>
                            <?php if (!$emailAddress->getIsPrimary()) { ?>
                                <a href="<?php echo $this->url('settings/email/primary', [
                                    'id' => $emailAddress->getId()->toString(),
                                ]); ?>" class="zui-button">Make primary</a>
                            <?php } ?>
                        <?php } else { ?>
                            <a href="<?php echo $this->url('settings/email/verify', [
                                'id' => $emailAddress->getId()->toString(),
                            ]); ?>" class="zui-button">
                                <i class="zui-icon zui-icon-check"></i>
                                Verify
                            </a>
                        <?php } ?>

                        <?php if ($emailAddress->getIsPrimary()) { ?>
                            <a href="<?php echo $this->url('settings/email/delete', [
                                'id' => $emailAddress->getId()->toString(),
                            ]); ?>" class="zui-button" disabled aria-disabled="true">Delete</a>
                        <?php } else { ?>
                            <a href="<?php echo $this->url('settings/email/delete', [
                                'id' => $emailAddress->getId()->toString(),
                            ]); ?>" class="zui-button">Delete</a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

    <p class="text-right">
        <a href="<?php echo $this->url('settings/email/add'); ?>" class="zui-button">Add e-mail address</a>
    </p>
<?php } ?>
