<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-users';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

?>

<div class="zui-toolbar">
    <div class="zui-toolbar-primary">
        <h2>Permissions</h2>
    </div>
</div>

<?php if (count($this->permissions) === 0) { ?>
    <div class="zui-alert">
        <p>
            No permissions found.
        </p>
    </div>
<?php } else { ?>
<table class="zui-table zui-table-striped zui-table-list">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->permissions as $name => $description) { ?>
        <tr>
            <td><?php echo $this->escapeHtml($this->translate($name, 'permissions')); ?></td>
            <td><?php echo $this->escapeHtml($this->translate($description, 'permissions')); ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php } ?>
