<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-system';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

?>

<div class="zui-toolbar">
    <div class="zui-toolbar-primary">
        <h2><?php echo $this->translate('pageAdminTitleCron'); ?></h2>
    </div>

    <div class="zui-toolbar-secondary">
        <div class="zui-button-group">
            <a href="<?php echo $this->url('admin/system/cron/create'); ?>" class="zui-button">Create</a>
        </div>
    </div>
</div>

<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_DEFAULT); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_WARNING); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_INFO); ?>

<?php if (count($this->cronjobs) !== 0) { ?>
    <table class="zui-table zui-table-bordered zui-table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Pattern</th>
                <th>Command</th>
                <th>Active</th>
                <th class="zui-text-right">Operations</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->cronjobs as $cronjob) { ?>
                <tr>
                    <td><?php echo $this->escapeHtml($cronjob->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($cronjob->getPattern()); ?></td>
                    <td><?php echo $this->escapeHtml($cronjob->getCommand()); ?></td>
                    <td><?php echo $this->escapeHtml($cronjob->getActive() ? 'Yes' : 'No'); ?></td>
                    <td class="zui-text-right">
                        <a href="<?php echo $this->url('admin/system/cron/update', [
                            'id' => $cronjob->getId(),
                        ]); ?>">Update</a>
                        -
                        <a href="<?php echo $this->url('admin/system/cron/delete', [
                            'id' => $cronjob->getId(),
                        ]); ?>">Delete</a>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } else { ?>
    <p>
        No cronjobs have been installed.
        <a href="<?php echo $this->url('admin/system/cron/create'); ?>">Would you like to create one?</a>
    </p>
<?php } ?>
