<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-system';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

?>

<h2><?php echo $this->translate('pageAdminTitleCache'); ?></h2>

<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_DEFAULT); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_WARNING); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_INFO); ?>

<table class="zui-table zui-table-bordered zui-table-striped">
    <thead>
        <tr>
            <th>Type</th>
            <th>Size</th>
            <th class="zui-text-right">Operations</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->cacheItems as $cacheItem) { ?>
        <tr>
            <td><?php echo $this->escapeHtml($cacheItem['label']); ?></td>
            <td><?php echo $this->escapeHtml($this->zourceBytes($cacheItem['size'])); ?></td>
            <td class="zui-text-right">
                <a href="<?php echo $this->url('admin/system/cache/clear', [
                    'id' => $cacheItem['id'],
                ]); ?>" title="">Clear cache</a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>

