<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-users';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

?>

<h2>Directories</h2>

<table class="zui-table zui-table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th class="zui-text-right">Operations</th>
        </tr>
    </thead>
</table>
