<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-users';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

?>

<div class="zui-toolbar">
    <div class="zui-toolbar-primary">
        <h2>Directories</h2>
    </div>
</div>

<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_DEFAULT); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_WARNING); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_INFO); ?>

<table class="zui-table zui-table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th class="zui-text-right">Priority</th>
            <th class="zui-text-right">Operations</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->directories as $directory) { ?>
            <tr>
                <td><?php echo $this->escapeHtml($this->translate($directory->getLabel())); ?></td>
                <td class="zui-text-right">
                    <a href="<?php echo $this->url('admin/usermanagement/directories/move-up', [
                        'type' => $directory->getType(),
                    ]); ?>">Up</a>
                    -
                    <a href="<?php echo $this->url('admin/usermanagement/directories/move-down', [
                        'type' => $directory->getType(),
                    ]); ?>">Down</a>
                </td>
                <td class="zui-text-right">
                    <?php if ($directory->getUpdateRouteName()) { ?>
                        <a href="<?php echo $this->url(
                            $directory->getUpdateRouteName(),
                            array_merge([
                                'type' => $directory->getType(),
                            ], $directory->getUpdateRouteParams()),
                            $directory->getUpdateRouteOptions()
                        ); ?>">Edit</a> -
                    <?php } ?>

                    <?php if ($directory->getEnabled()) { ?>
                        <a href="<?php echo $this->url('admin/usermanagement/directories/disable', [
                            'type' => $directory->getType(),
                        ]); ?>">Disable</a>
                    <?php } else { ?>
                        <a href="<?php echo $this->url('admin/usermanagement/directories/enable', [
                            'type' => $directory->getType(),
                        ]); ?>">Enable</a>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>
