<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-users';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

?>

<div class="zui-toolbar">
    <div class="zui-toolbar-primary">
        <h2>Directories</h2>
    </div>
</div>

<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_DEFAULT); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_WARNING); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_INFO); ?>

<table class="zui-table zui-table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th style="width: 200px;">Priority</th>
            <th class="zui-text-right" style="width: 200px;">Operations</th>
        </tr>
    </thead>
    <tbody>
        <?php

        foreach ($this->directories as $type => $directory) {
            $enableRoute = 'admin/usermanagement/directories/enable';
            $enableRouteParams = array_merge(
                [
                    'type' => $type,
                ],
                $directory['enable_route_params']
            );
            $enableRouteOptions = $directory['enable_route_options'];

            $disableRoute = 'admin/usermanagement/directories/disable';
            $disableRouteParams = array_merge(
                [
                    'type' => $type,
                ],
                $directory['disable_route_params']
            );
            $disableRouteOptions = $directory['disable_route_options'];

            $updateRoute = $directory['update_route_name'] ? $directory['update_route_name'] : null;
            $updateRouteParams = array_merge(
                [
                    'type' => $type,
                ],
                $directory['update_route_params']
            );
            $updateRouteOptions = $directory['update_route_options'];

            ?>
            <tr>
                <td><?php echo $this->escapeHtml($this->translate($directory['label'])); ?></td>
                <td>
                    <a href="<?php echo $this->url('admin/usermanagement/directories/move-up', [
                        'type' => $type,
                    ]); ?>">Up</a>
                    -
                    <a href="<?php echo $this->url('admin/usermanagement/directories/move-down', [
                        'type' => $type,
                    ]); ?>">Down</a>
                </td>
                <td class="zui-text-right">
                    <?php if ($directory['update_route_name']) { ?>
                        <a href="<?php echo $this->url($updateRoute, $updateRouteParams, $updateRouteOptions); ?>">Edit</a> -
                    <?php } ?>

                    <?php if ($directory['enabled']) { ?>
                        <a href="<?php echo $this->url($disableRoute, $disableRouteParams, $disableRouteOptions); ?>">Disable</a>
                    <?php } else { ?>
                        <a href="<?php echo $this->url($enableRoute, $enableRouteParams, $enableRouteOptions); ?>">Enable</a>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>
