<?php
$operation = $this->operation;
$service = $this->service;
$generalFields = $service->getFields('input_filter');
$httpMethodFields = $service->getFields($operation->getHttpMethod());
$isEntity = $this->isEntity;
?>

<h3 id="<?php echo $this->escapeHtmlAttr($isEntity ? 'entity-' . $operation->getHttpMethod() : 'collection-' . $operation->getHttpMethod()); ?>">
    <span><?php echo $this->escapeHtml($operation->getHttpMethod()) ?></span>

    <?php echo $this->escapeHtml($isEntity ? $service->getRoute() : $this->agServicePath($service, $operation)); ?>
</h3>

<p>
    <?php echo $this->escapeHtml($operation->getDescription()) ?>
</p>

<?php if (!empty($generalFields) || !empty($httpMethodFields)): ?>
    <h4>Fields</h4>
    <table class="zui-table zui-table-striped zui-table-bordered">
        <thead>
            <tr>
                <th>Field</th>
                <th>Type</th>
                <th>Description</th>
                <th class="center-block">Required</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (is_array($generalFields)):
                foreach ($generalFields as $field): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($field->getName()) ?></td>
                        <td><?php echo $this->escapeHtml($field->getType() ?: '') ?></td>
                        <td><?php echo $this->escapeHtml($field->getDescription()) ?></td>
                        <td class="center-block"><span
                                class="badge"><?php echo ($field->isRequired()) ? 'YES' : 'NO' ?></td>
                    </tr>
                    <?php
                endforeach;
            endif;
            ?>
            <?php
            if (is_array($httpMethodFields)):
                foreach ($httpMethodFields as $field): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($field->getName()) ?></td>
                        <td><?php echo $this->escapeHtml($field->getType() ?: '') ?></td>
                        <td><?php echo $this->escapeHtml($field->getDescription()) ?></td>
                        <td class="center-block"><span
                                class="badge"><?php echo ($field->isRequired()) ? 'YES' : 'NO' ?></td>
                    </tr>
                    <?php
                endforeach;
            endif;
            ?>
        </tbody>
    </table>
<?php endif ?>

<h4>Request</h4>

<div class="panel-body">
    <h5>Headers</h5>

    <table class="zui-table zui-table-striped zui-table-list zui-table-bordered">
        <thead>
            <tr>
                <th>Header</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Accept</td>
                <td class="list-group"><?php echo $this->agAcceptHeaders($service, $this) ?></td>
            </tr>
            <?php if (in_array($operation->getHttpMethod(), array('POST', 'PUT', 'PATCH'))): ?>
                <tr>
                    <td>Content-Type</td>
                    <td class="list-group"><?php echo $this->agContentTypeHeaders($service, $this) ?></td>
                </tr>
            <?php endif ?>
            <?php if ($operation->requiresAuthorization()): ?>
                <tr>
                    <td>Authorization</td>
                    <td class="text-muted">HTTP Basic, HTTP Digest, or OAuth2 Bearer token (check
                        API provider for details)
                    </td>
                </tr>
            <?php endif ?>
    </table>

    <?php if (!in_array($operation->getHttpMethod(), array('GET', 'DELETE'))): ?>
        <h5>Body</h5>
        <pre class="pre-scrollable"><?php echo $operation->getRequestDescription() ?></pre>
    <?php endif ?>
</div>

<h4>Response</h4>


<h5>Status Codes</h5>

<table class="zui-table zui-table-striped zui-table-list zui-table-bordered">
    <thead>
        <tr>
            <th>Code</th>
            <th>Message</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($operation->getResponseStatusCodes() as $statusCode) { ?>
            <tr>
                <td><span
                        class="zui-status zui-status-subtle"><?php echo $this->escapeHtml($statusCode['code']); ?></span>
                </td>
                <td><?php echo $this->escapeHtml($statusCode['message']); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<h4>Headers</h4>

<table class="zui-table zui-table-striped zui-table-list zui-table-bordered">
    <thead>
        <tr>
            <th>Header</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Content-Type</td>
            <td class="list-group"><?php echo $this->agAcceptHeaders($service, $this) ?></td>
        </tr>
        <tr>
            <td>Allow</td>
            <td class="text-muted">Comma-separated list of all HTTP methods allowed</td>
        </tr>
</table>

<?php if ($operation->getHttpMethod() !== 'DELETE'): ?>
    <h5>Body</h5>

    <pre><?php echo $operation->getResponseDescription(); ?></pre>
<?php endif ?>
