<?php

$service = $this->service;
$entityOperations = $service->getEntityOperations();

?>

<h2 class="panel-title"><?php echo $this->escapeHtml($service->getName()) ?></h2>

<p>
    <?php echo $this->escapeHtml($service->getDescription()) ?>
</p>

<?php foreach ($service->getOperations() as $operation) {
    echo $this->render('zource-application/apigility/operation', array(
        'operation' => $operation,
        'service' => $service,
        'isEntity' => false,
    ));
} ?>

<?php if ($entityOperations) {
    foreach ($entityOperations as $j => $operation) {
        echo $this->render('zource-application/apigility/operation', array(
            'operation' => $operation,
            'service' => $service,
            'isEntity' => true,
        ));
    }
} ?>
