<?php

$service = $this->service;

if ($this->showDetails === null) {
    $this->showDetails = true;
}

?>

<h2><a href="<?php echo $this->url('zf-apigility/documentation',
        [
            'api' => $this->service->getApi()->getName(),
            'version' => $this->service->getApi()->getVersion(),
            'service' => $service->getName(),
        ]
    ); ?>"><?php echo $this->escapeHtml($service->getName()) ?></a></h2>

<p>
    <?php echo $this->escapeHtml($service->getDescription()) ?>
</p>

<?php if (!$this->showDetails) { ?>

    <table class="zui-table zui-table-striped">
        <thead>
            <tr>
                <th style="width: 10%;">Type</th>
                <th style="width: 10%;">Method</th>
                <th>Route</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($service->getOperations() as $operation) { ?>
                <tr>
                    <td>Collection</td>
                    <td>
                        <span class="zui-status zui-status-subtle">
                            <?php echo $this->escapeHtml($operation->getHttpMethod()); ?>
                        </span>
                    </td>
                    <td>
                        <?php echo $this->escapeHtml($this->agServicePath($service, $operation)); ?>
                    </td>
                </tr>
            <?php } ?>

            <?php if ($service->getEntityOperations()) { ?>
                <?php foreach ($service->getEntityOperations() as $operation) { ?>
                    <tr>
                        <td>Entity</td>
                        <td>
                            <span class="zui-status zui-status-subtle">
                                <?php echo $this->escapeHtml($operation->getHttpMethod()); ?>
                            </span>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($service->getRoute()); ?>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>
        </tbody>
    </table>

<?php } else { ?>

    <?php

    foreach ($service->getOperations() as $operation) {
        echo $this->render('zource-application/apigility/operation', [
            'operation' => $operation,
            'service' => $service,
            'isEntity' => false,
        ]);
    }

    if ($service->getEntityOperations()) {
        foreach ($service->getEntityOperations() as $j => $operation) {
            echo $this->render('zource-application/apigility/operation', [
                'operation' => $operation,
                'service' => $service,
                'isEntity' => true,
            ]);
        }
    }

    ?>

<?php } ?>
