<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-system';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

?>

<div class="zui-toolbar">
    <div class="zui-toolbar-primary">
        <h2><?php echo $this->translate('pageAdminTitleDaemon'); ?></h2>
    </div>

    <div class="zui-toolbar-secondary">
        <div class="zui-button-group">
            <a href="<?php echo $this->url('admin/system/daemon'); ?>" class="zui-button">Start</a>
            <a href="<?php echo $this->url('admin/system/daemon'); ?>" class="zui-button disabled">Restart</a>
            <a href="<?php echo $this->url('admin/system/daemon'); ?>" class="zui-button disabled">Stop</a>
        </div>
    </div>
</div>

<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_DEFAULT); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_WARNING); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR); ?>
<?php echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_INFO); ?>

<h3>Stats</h3>

<table class="zui-table zui-table-list">
    <tbody>
        <?php foreach ($this->stats as $name => $value) { ?>
        <tr>
            <td><?php echo $this->translate($name); ?></td>
            <td><?php echo $this->escapeHtml($value); ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>

<h3>Tubes</h3>

<table class="zui-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Jobs Buried</th>
            <th>Jobs Delayed</th>
            <th>Jobs Ready</th>
            <th>Jobs Reserved</th>
            <th>Jobs Urgent</th>
            <th>Workers Waiting</th>
            <th>Total Jobs</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->tubes as $tube) { ?>
            <tr>
                <td><?php echo $this->escapeHtml($tube['name']); ?></td>
                <td><?php echo $this->escapeHtml($tube['buried']); ?></td>
                <td><?php echo $this->escapeHtml($tube['delayed']); ?></td>
                <td><?php echo $this->escapeHtml($tube['ready']); ?></td>
                <td><?php echo $this->escapeHtml($tube['reserved']); ?></td>
                <td><?php echo $this->escapeHtml($tube['urgent']); ?></td>
                <td><?php echo $this->escapeHtml($tube['waiting']); ?></td>
                <td><?php echo $this->escapeHtml($tube['total']); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
