<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return [
    'ZF\\DevelopmentMode',
    'ZF\\Apigility',
    'ZF\\Apigility\\Provider',
    'ZF\\Apigility\\Documentation',
    'ZF\\Apigility\\Documentation\\Swagger',
    'ZF\\ApiProblem',
    'ZF\\Configuration',
    'ZF\\OAuth2',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'DoctrineModule',
    'DoctrineORMModule',
    'ZourceApplication',
    'ZourceDaemon',
    'ZourceContact',
    'ZourceUser',
];
