<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('layoutUserProfileTitle');
$this->placeholder('layout')->pageMenu = 'user-settings';

$this->form->setAttribute('action', $this->url('settings/account'));
$this->form->setAttribute('method', 'post');
$this->form->prepare();

?>

<h2><?php echo $this->translate('pageUserAccountTitle'); ?></h2>

<?php echo $this->form()->openTag($this->form); ?>
    <?php echo $this->formHidden($this->form->get('token')); ?>
<?php echo $this->formElementErrors($this->form->get('token')); ?>

    <div class="zui-field-group">
        <?php echo $this->formLabel($this->form->get('currentPassword')); ?>
        <?php echo $this->formPassword($this->form->get('currentPassword')); ?>
        <?php echo $this->zourceFormDescription($this->form->get('currentPassword')); ?>
        <?php echo $this->formElementErrors($this->form->get('currentPassword')); ?>
    </div>

    <div class="zui-field-group">
        <?php echo $this->formLabel($this->form->get('newPassword')); ?>
        <?php echo $this->formPassword($this->form->get('newPassword')); ?>
        <?php echo $this->zourceFormDescription($this->form->get('newPassword')); ?>
        <?php echo $this->formElementErrors($this->form->get('newPassword')); ?>
    </div>

    <div class="zui-field-group">
        <?php echo $this->formLabel($this->form->get('confirmPassword')); ?>
        <?php echo $this->formPassword($this->form->get('confirmPassword')); ?>
        <?php echo $this->zourceFormDescription($this->form->get('confirmPassword')); ?>
        <?php echo $this->formElementErrors($this->form->get('confirmPassword')); ?>
    </div>

    <div class="zui-buttons-container">
        <div class="zui-buttons">
            <?php echo $this->formSubmit($this->form->get('submit')); ?>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>
