<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php echo $this->partial('partial/head'); ?>
    </head>
    <body>
        <div id="wrapper">
            <?php echo $this->partial('partial/top-bar'); ?>

            <section id="zource-content" role="main">
                <div class="zui-page-panel">
                    <div class="zui-page-content">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </section>

            <?php echo $this->partial('partial/footer'); ?>
        </div>

        <?php echo $this->partial('partial/scripts'); ?>
    </body>
</html>
