<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php echo $this->partial('partial/head'); ?>
    </head>
    <body>
        <div id="wrapper">
            <?php echo $this->partial('partial/top-bar'); ?>

            <section id="zource-content" role="main">
                <div id="zui-page-header" class="page-header">
                    <div class="zui-page-header-inner">
                        <?php if (isset($this->placeholder('layout')->pageImage)) { ?>
                            <div class="zui-page-header-image">
                                <img src="<?php echo $this->escapeHtmlAttr($this->placeholder('layout')->pageImage); ?>"
                                     class="zui-image-round">
                            </div>
                        <?php } ?>

                        <div class="zui-page-header-main">
                            <h1><?php echo $this->placeholder('layout')->pageTitle; ?></h1>
                        </div>

                        <?php if (isset($this->placeholder('layout')->pageHeaderMenu)) { ?>
                            <div class="zui-page-header-actions">
                                <div class="zui-button-group">
                                    <?php foreach ($this->placeholder('layout')->pageHeaderMenu as $url => $label) { ?>
                                        <a href="<?php echo $this->escapeHtmlAttr($url); ?>" class="zui-button">
                                            <?php echo $this->escapeHtml($this->translate($label)); ?>
                                        </a>
                                    <?php } ?>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>

                <?php echo $this->content; ?>
            </section>

            <?php echo $this->partial('partial/footer'); ?>
        </div>

        <?php echo $this->partial('partial/scripts'); ?>
    </body>
</html>
