<?php
$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageContactsTitle');
$this->placeholder('layout')->pageMenu = 'contacts-directory';
?>

<div id="zource-contacts-directory">
    <?php if ($this->contactsPaginator->count() === 0) { ?>
        <div class="zui-alert">
            <p>
                <?php echo $this->translate('No contacts found.'); ?>
            </p>
        </div>
    <?php } else { ?>
        <ul>
            <?php foreach ($this->contactsPaginator as $contact) { ?>
                <li>
                    <h2>
                        <a href="<?php echo $this->url('contacts/view', [
                            'type' => $contact->getType(),
                            'id' => $contact->getId()->toString(),
                        ]); ?>">
                            <?php echo $this->escapeHtml($contact->getDisplayName()); ?>
                        </a>
                    </h2>
                    <p>
                        <a href="<?php echo $this->url('contacts/view', [
                            'type' => $contact->getType(),
                            'id' => $contact->getId()->toString(),
                        ]); ?>">
                            <?php echo $this->zourceContactAvatar($contact); ?>
                        </a>
                    </p>
                </li>
            <?php } ?>
        </ul>
    <?php } ?>
</div>
