<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-system';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

$this->installForm->setAttribute('action', $this->url('admin/system/plugins'));
$this->installForm->setAttribute('method', 'post');
$this->installForm->prepare();

?>

<h2><?php echo $this->translate('pageAdminTitlePlugin'); ?></h2>

<?php if (count($this->plugins) !== 0) { ?>
<table class="zui-table zui-table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th class="zui-text-right">Operations</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->plugins as $plugin) { ?>
        <tr>
            <td>
                <?php echo $this->escapeHtml($plugin->getName()); ?><br />
                <small><?php echo $this->escapeHtml($plugin->getDescription()); ?></small>
            </td>
            <td class="zui-text-right">
                <?php if ($plugin->getActive()) { ?>
                    <a href="<?php echo $this->url('admin/system/plugins/deactivate', [
                        'id' => $plugin->getId(),
                    ]); ?>">Deactivate</a>
                <?php } else { ?>
                    <a href="<?php echo $this->url('admin/system/plugins/activate', [
                        'id' => $plugin->getId(),
                    ]); ?>">Activate</a>
                <?php } ?>
                -
                <a href="<?php echo $this->url('admin/system/plugins/uninstall', [
                    'id' => $plugin->getId(),
                ]); ?>">Uninstall</a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php } else { ?>
    <p>
        No plugins installed.
    </p>
<?php } ?>

<h3>Install Plugin</h3>

<p>You can either download a plugin file from an external location or upload a zip file.</p>

<?php echo $this->form()->openTag($this->installForm); ?>
    <?php echo $this->formHidden($this->installForm->get('token')); ?>

    <div class="zui-field-group">
        <?php echo $this->formLabel($this->installForm->get('location')); ?>
        <?php echo $this->formText($this->installForm->get('location')); ?>
        <?php echo $this->zourceFormDescription($this->installForm->get('location')); ?>
        <?php echo $this->formElementErrors($this->installForm->get('location')); ?>
    </div>

    <div class="zui-field-group">
        <?php echo $this->formLabel($this->installForm->get('plugin')); ?>
        <div class="zui-button-file">
            <?php echo $this->formFile($this->installForm->get('plugin')); ?>

            <span>Choose File</span>
        </div>
        <?php echo $this->zourceFormDescription($this->installForm->get('plugin')); ?>
        <?php echo $this->formElementErrors($this->installForm->get('plugin')); ?>
    </div>

    <div class="zui-buttons-container">
        <div class="zui-buttons">
            <?php echo $this->formSubmit($this->installForm->get('submit')); ?>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>

