<?php

use ZourceContact\Entity\Company;

$this->layout('layout/page-header');

/** @var Company $company */
$company = $this->company;

$this->placeholder('layout')->pageTitle = $this->translate('pageContactsTitle');
$this->placeholder('layout')->pageMenu = 'contacts-directory';

$this->contactForm->setAttribute('action', $this->url('contacts/company/update', [
    'id' => $this->company->getId()->toString(),
]));
$this->contactForm->setAttribute('method', 'post');
$this->contactForm->prepare();

?>

<h2>Edit details of <?php echo $this->escapeHtml($company->getDisplayName()); ?></h2>

<?php echo $this->form()->openTag($this->contactForm); ?>
<?php echo $this->formHidden($this->contactForm->get('token')); ?>
<?php echo $this->zourceContactForm()->render($this->contactForm, 'company'); ?>

<div class="zui-buttons-container">
    <div class="zui-buttons">
        <?php echo $this->formSubmit($this->contactForm->get('submit')); ?>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>
<?php echo $this->zourceContactForm()->renderAdditional($this->contactForm, 'company'); ?>
