<?php

$this->layout('layout/page-header');

/** @var \ZourceContact\Entity\Company $company */
$company = $this->company;

$this->placeholder('layout')->pageTitle = $company->getDisplayName();
$this->placeholder('layout')->pageMenu = 'view-contact';
$this->placeholder('layout')->pageImage = $this->zourceContactAvatar()->getUrl($company->getId());

?>

<table class="zui-table-list">
    <tbody>
        <tr>
            <td>Created on</td>
            <td><?php echo $this->escapeHtml($company->getCreationDate()->format('r')); ?></td>
        </tr>
        <tr>
            <td>Last updated on</td>
            <td><?php echo $this->escapeHtml($company->getLastUpdated()->format('r')); ?></td>
        </tr>
        <tr>
            <td>Display name</td>
            <td><?php echo $this->escapeHtml($company->getDisplayName()); ?></td>
        </tr>
        <tr>
            <td>Name</td>
            <td><?php echo $this->escapeHtml($company->getName()); ?></td>
        </tr>
        <tr>
            <td>Phone numbers</td>
            <td></td>
        </tr>
        <tr>
            <td>E-mail addresses</td>
            <td></td>
        </tr>
        <tr>
            <td>Links</td>
            <td></td>
        </tr>
        <tr>
            <td>Dates</td>
            <td></td>
        </tr>
        <tr>
            <td>Notes</td>
            <td><?php echo nl2br($this->escapeHtml($company->getNotes())); ?></td>
        </tr>
    </tbody>
</table>
