<?php

$this->layout('layout/page-header');

$this->placeholder('layout')->pageTitle = $this->translate('pageAdminTitle');
$this->placeholder('layout')->pageMenu = 'admin-users';
$this->placeholder('layout')->pageNavGroupPrimary = 'admin-navgroup';

$this->accountForm->setAttribute('action', $this->url('admin/usermanagement/accounts/update', [
    'id' => $this->account->getId(),
]));
$this->accountForm->setAttribute('method', 'post');

?>

<h2>Update Account</h2>

<?php echo $this->form()->openTag($this->accountForm); ?>
<?php echo $this->formHidden($this->accountForm->get('token')); ?>

<div class="zui-field-group">
    <span class="zui-form-label"><?php echo $this->accountForm->get('status')->getLabel(); ?></span>

    <div class="zui-field-group-inner">
        <?php echo $this->formRadio($this->accountForm->get('status')); ?>
    </div>

    <?php echo $this->zourceFormDescription($this->accountForm->get('status')); ?>
    <?php echo $this->formElementErrors($this->accountForm->get('status')); ?>
</div>

<div class="zui-buttons-container">
    <div class="zui-buttons">
        <?php echo $this->formSubmit($this->accountForm->get('submit')); ?>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>
