<?php $this->layout('layout/dialog'); ?>

<h2><?php echo $this->translate('pageRequestPasswordTitle'); ?></h2>

<?php echo $this->form()->openTag($this->requestPasswordForm); ?>
    <?php echo $this->formHidden($this->requestPasswordForm->get('token')); ?>

    <div class="zui-field-group">
        <?php echo $this->formLabel($this->requestPasswordForm->get('email')); ?>
        <?php echo $this->formText($this->requestPasswordForm->get('email')); ?>
        <?php echo $this->zourceFormDescription($this->requestPasswordForm->get('email')); ?>
        <?php echo $this->formElementErrors($this->requestPasswordForm->get('email')); ?>
    </div>

    <div class="zui-buttons-container">
        <div class="zui-buttons">
            <?php echo $this->formSubmit($this->requestPasswordForm->get('submit')); ?>

            <a href="<?php echo $this->url('login'); ?>" class="zui-button zui-button-link cancel">
                <?php echo $this->translate('requestPasswordFormCancel'); ?>
            </a>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>
