<?php $this->layout('layout/dialog'); ?>

<h2><?php echo $this->translate('pageResetPasswordTitle'); ?></h2>

<?php echo $this->form()->openTag($this->resetPasswordForm); ?>
    <?php echo $this->formHidden($this->resetPasswordForm->get('token')); ?>

    <?php if ($this->code) { ?>
        <?php echo $this->formHidden($this->resetPasswordForm->get('code')); ?>
    <?php } else { ?>
        <div class="zui-field-group">
            <?php echo $this->formLabel($this->resetPasswordForm->get('code')); ?>
            <?php echo $this->formText($this->resetPasswordForm->get('code')); ?>
            <?php echo $this->zourceFormDescription($this->resetPasswordForm->get('code')); ?>
            <?php echo $this->formElementErrors($this->resetPasswordForm->get('code')); ?>
        </div>
    <?php } ?>

    <div class="zui-field-group">
        <?php echo $this->formLabel($this->resetPasswordForm->get('credential')); ?>
        <?php echo $this->formPassword($this->resetPasswordForm->get('credential')); ?>
        <?php echo $this->zourceFormDescription($this->resetPasswordForm->get('credential')); ?>
        <?php echo $this->formElementErrors($this->resetPasswordForm->get('credential')); ?>
    </div>
    
    <div class="zui-field-group">
        <?php echo $this->formLabel($this->resetPasswordForm->get('verification')); ?>
        <?php echo $this->formPassword($this->resetPasswordForm->get('verification')); ?>
        <?php echo $this->zourceFormDescription($this->resetPasswordForm->get('verification')); ?>
        <?php echo $this->formElementErrors($this->resetPasswordForm->get('verification')); ?>
    </div>

    <div class="zui-buttons-container">
        <div class="zui-buttons">
            <?php echo $this->formSubmit($this->resetPasswordForm->get('submit')); ?>

            <a href="<?php echo $this->url('login'); ?>" class="zui-button zui-button-link cancel">
                <?php echo $this->translate('resetPasswordFormCancel'); ?>
            </a>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>
