<div class="zui-page-sidebar zui-page-sidebar-left">
    <nav class="zui-navgroup zui-navgroup-vertical">
        <div class="zui-navgroup-inner">
            <div class="zui-nav-heading"><strong>Overview</strong></div>

            <ul class="zui-nav">
                <li role="presentation">
                    <a href="<?php echo $this->url('zf-apigility/documentation'); ?>#current-version">
                        Current Version
                    </a>
                </li>
                <li role="presentation">
                    <a href="<?php echo $this->url('zf-apigility/documentation'); ?>#schema">
                        Schema
                    </a>
                </li>
                <li role="presentation">
                    <a href="<?php echo $this->url('zf-apigility/documentation'); ?>#http-errors">
                        HTTP Errors
                    </a>
                </li>
                <li role="presentation">
                    <a href="<?php echo $this->url('zf-apigility/documentation'); ?>#http-redirects">
                        HTTP Redirects
                    </a>
                </li>
                <li role="presentation">
                    <a href="<?php echo $this->url('zf-apigility/documentation'); ?>#http-verbs">
                        HTTP Verbs
                    </a>
                </li>
                <li role="presentation">
                    <a href="<?php echo $this->url('zf-apigility/documentation'); ?>#authentication">
                        Authentication
                    </a>
                </li>
                <li role="presentation">
                    <a href="<?php echo $this->url('zf-apigility/documentation'); ?>#user-agent">
                        User Agent
                    </a>
                </li>
                <li role="presentation">
                    <a href="<?php echo $this->url('zf-apigility/documentation'); ?>#parameters">
                        Parameters
                    </a>
                </li>
                <li role="presentation">
                    <a href="<?php echo $this->url('zf-apigility/documentation'); ?>#dates">
                        Dates
                    </a>
                </li>
                <li role="presentation">
                    <a href="<?php echo $this->url('zf-apigility/documentation'); ?>#pagination">
                        Pagination
                    </a>
                </li>
            </ul>

            <?php if (isset($this->apis)) { ?>
                <div class="zui-nav-heading"><strong>API List</strong></div>

                <ul class="zui-nav">
                    <?php

                    foreach ($this->apis as $api) {
                        foreach ($api['versions'] as $version) {
                            ?>
                            <li role="presentation">
                                <a href="<?php echo $this->url(
                                    'zf-apigility/documentation',
                                    [
                                        'api' => $api['name'],
                                        'version' => $version,
                                    ]
                                ); ?>" title="All contacts">
                                    <?php echo $this->escapeHtml($api['name']); ?>
                                </a>
                            </li>
                            <?php
                        }
                    }

                    ?>
                </ul>
            <?php } elseif ($this->documentation instanceof \ZF\Apigility\Documentation\Api) { ?>
                <div class="zui-nav-heading"><strong>API Services</strong></div>

                <ul class="zui-nav">
                    <?php foreach ($this->documentation->getServices() as $service) { ?>
                        <li role="presentation">
                            <a href="<?php echo $this->url('zf-apigility/documentation',
                                [
                                    'api' => $this->documentation->getName(),
                                    'version' => $this->documentation->getVersion(),
                                    'service' => $service->getName(),
                                ]
                            ); ?>" title="<?php echo $this->escapeHtmlAttr($service->getName()); ?>">
                                <?php echo $this->escapeHtml($service->getName()); ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            <?php } elseif ($this->documentation instanceof \ZF\Apigility\Documentation\Service) { ?>
                <div class="zui-nav-heading"><strong>API Services</strong></div>

                <ul class="zui-nav">
                    <?php foreach ($this->documentation->getApi()->getServices() as $service) { ?>
                        <li role="presentation">
                            <a href="<?php echo $this->url('zf-apigility/documentation',
                                [
                                    'api' => $this->documentation->getApi()->getName(),
                                    'version' => $this->documentation->getApi()->getVersion(),
                                    'service' => $service->getName(),
                                ]
                            ); ?>" title="<?php echo $this->escapeHtmlAttr($service->getName()); ?>">
                                <?php echo $this->escapeHtml($service->getName()); ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>

                <?php if ($this->documentation->getOperations()) { ?>
                    <div class="zui-nav-heading"><strong>Collection Operations</strong></div>

                    <ul class="zui-nav">
                        <?php foreach ($this->documentation->getOperations() as $operation) { ?>
                            <li role="presentation">
                                <a href="#collection-<?php echo $this->escapeHtmlAttr($operation->getHttpMethod()); ?>"
                                   title="<?php echo $this->escapeHtmlAttr($operation->getHttpMethod()); ?>">
                                    <?php echo $this->escapeHtml($operation->getHttpMethod()); ?>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                <?php } ?>

                <?php if ($this->documentation->getEntityOperations()) { ?>
                    <div class="zui-nav-heading"><strong>Entity Operations</strong></div>

                    <ul class="zui-nav">
                        <?php foreach ($this->documentation->getEntityOperations() as $operation) { ?>
                            <li role="presentation">
                                <a href="#entity-<?php echo $this->escapeHtmlAttr($operation->getHttpMethod()); ?>"
                                   title="<?php echo $this->escapeHtmlAttr($operation->getHttpMethod()); ?>">
                                    <?php echo $this->escapeHtml($operation->getHttpMethod()); ?>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                <?php } ?>
            <?php } ?>
        </div>
    </nav>
</div>
