<footer>
    <ul>
        <li><a href="http://github.com/zource"><?php echo $this->translate('layoutFooterMenuZource'); ?></a></li>
        <li><a href="http://github.com/zource"><?php echo $this->translate('layoutFooterMenuAbout'); ?></a></li>
        <li><a href="http://github.com/zource"><?php echo $this->translate('layoutFooterMenuHelp'); ?></a></li>
        <li><a href="<?php echo $this->url('zf-apigility/documentation'); ?>"><?php echo $this->translate('layoutFooterMenuApi'); ?></a></li>
    </ul>

    <ul>
        <li><a href="http://github.com/zource"><?php echo $this->translate('layoutFooterPoweredByLicenseOpenSource'); ?></a></li>
    </ul>
</footer>
