<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<?php echo $this->headTitle('headTitle'); ?>

<link href="<?php echo $this->basePath('css/zource.css'); ?>" media="screen" rel="stylesheet" type="text/css">
<?php

echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
echo $this->headLink(array('rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png')));
echo $this->headScript();

?>
